services:
  laravel.test:
    build:
      context: .
      dockerfile: ./dockerfile   # now includes Redis server
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${PHP_FPM_PORT:-8080}:9000'   # PHP-FPM exposed port
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}' # Frontend dev server
    environment:
      # Point to the redis service in this compose network
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: 6379
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'   # Local code for hot reload
    networks:
      - statamic
    depends_on:
      - mysql
      - minio
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel.test
    networks:
      - statamic

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
    volumes:
      - 'statamic-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - statamic
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  minio:
    build:
      context: .
      dockerfile: ./docker/dockerfile.minio
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
    volumes:
      - 'statamic-minio:/data'
      - ./docker/docker-entrypoint-minio.sh:/usr/local/bin/entrypoint-minio.sh
    networks:
      - statamic
    command: ["sh", "/usr/local/bin/entrypoint-minio.sh"]
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      retries: 3
      timeout: 5s

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'statamic-redis:/data'
    networks:
      - statamic
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      retries: 5
      timeout: 2s

networks:
  statamic:
    driver: bridge

volumes:
  statamic-mysql:
    driver: local
  statamic-minio:
    driver: local
